### PR TITLE
fix: Fixed the width of the Input tag and placed the input in new line

### PR DESCRIPTION
**Pull request by vishalpawarR**
Hey this is the final output refer the below screenshot.
screencapture-127-0-0-1-5173-2023-06-14-14_07_43

### CODE REVIEW

**Comment by ArshErgon** [comment]
Screenshot from 2023-06-14 13-50-09
your PR isn't updated I think, the changes its deleting are made by me in morning, can you please sync the branch

edit: its weird, the changes you made like the margin, I can see it on vercel but the PR is showing different code. On your PR what you are seeing?

**Comment by vishalpawarR** [comment]
Hey! I don't know how to sync branch but I directly sync forked from GitHub. Can you please help me?

Sorry I didn't know I need to check for updates before sending PRs This is my first day Open Source contribution my few PRs got accepted today.

I am seeing some conflicts as well not sure why!

**Comment by ArshErgon** [comment]
@vishalpawarR well its mostly from github, for me I can't see who forked my repos.
anyway,  there are some commands like
`git pull` or on the left bottom of vscode theres a two circle arrow which can sync, sync or pull only happened when you have updated something on cloud and its not updated on local machine (sometimes conflict occurs) 
you said you are new in open source but you still manages to create a new branch for the changes its not a noob move.
I'm telling you ways how you can update your repo
1. git pull (make sure to commit your changes, or else it will reset)
2. git fetch && git merge
3. git checkout main && git pull && git branch NEW_BRANCH_NAME && git switch NEW_BRANCH_NAME
the 3rd one, will take you to the main branch, it will update itself with github's present code, then a new branch will be created and will be switch to it.

Choose whatsoever will work for you. Ping me if you stuck anywhere.

you maybe seeing a conflict like
`>>>>`
SOME CODE
`>>>>`
`>>>>`
SOME CODE
`>>>>`

closely see the above and below code of `>>>` and then you will understand the upper code is the latest one and the below is old one, sometimes its vice-versa. Will suggest you to use git pull on master/main and create a new branch send me a PR then

**Comment by ArshErgon** [comment]
this issue has been solved: #21

**Pull request closed without merging**
